### PR TITLE
Localize me

### PR DESCRIPTION
**Pull request by tryxer**
add a button for geolocation

### CODE REVIEW

**Comment by mchristopher** [comment]
I'm not sure what this PR was for, but I've pulled in a newer version of the map app that includes geolocation. Does that do what you want?

**Comment by tryxer** [comment]
I wish creates a button to locate us directly because once the software launch The location must write if we did not locate in the beginning . after its software scan around us

**Comment by mchristopher** [comment]
I think this is already covered in the latest releases. Closing for now, please re-open if it doesn't fix the issue.

**Comment by tryxer** [comment]
Good job

**Pull request closed without merging**
