### PR TITLE
Update login.html

### PR DESCRIPTION
**Pull request by kking124**
I've added a google address lookup field to the location section

### CODE REVIEW

**Comment by petrusali** [comment]
Everytime I need to change location, I have to signout
How I can use change location in filter?

**Comment by kking124** [comment]
That filter appears to be non-functional from my testing. I don't believe it's currently usable. 

This pull request does not fix that issue.

**Comment by 93732** [comment]
@kking124 

how i do compile your version with main program?

**Comment by kking124** [comment]
Easiest way?

1. Download: https://github.com/kking124/PokemonGo-DesktopMap/blob/master/login.html
1. Go to the folder where you have the app saved.
1. Open the folder "resources"
1. Open the folder "app"
1. replace the existing login.html page with the one you downloaded.

**Comment by mchristopher** [comment]
I think this is fixed in the latest release of the map repo, though I'm happy to merge this in if you don't mind updating it to resolve conflicts.

**Comment by kking124** [comment]
I've not looked at main since I committed the pull; this wasn't a fix as much as a feature add - instead of needing to know the GPS coordinates on on the login page, you could enter an address and get its GPS coordinates from Google for it.

I'll check out main and resubmit if needed. When's your next release?

**Comment by kking124** [comment]
Just looked at login.html on current main, and this could still be added if you want. I'll re-branch and drop a new pull if you're done modding for the night.

See below for the way I changed the login screen:

image

As you can see, all I added was an address field below the GPS coords - if the address resolves on the Google geocode api, it fills those fields in for you.

**Comment by kking124** [comment]
Request Close.

See https://github.com/mchristopher/PokemonGo-DesktopMap/pull/253

**Pull request closed without merging**
